const testData = {
    employees: [
        {
            name: "Mandy",
            role: "care assistant",
            shift: {
                start: "08:00am",
                end: "12:00pm",
            },
        },
        // {
        //     name: "Mary",
        //     role: "care assistant",
        //     shift: {
        //         start: "12:00pm",
        //         end: "06:00pm",
        //     },
        // },
        {
            name: "Star",
            role: "nurse",
            shift: {
                start: "08:00am",
                end: "12:00pm",
            },
        },
        // {
        //     name: "John",
        //     role: "nurse",
        //     shift: {
        //         start: "12:00pm",
        //         end: "06:00pm",
        //     },
        // },
        {
            name: "Emily",
            role: "care assistant",
            shift: {
                start: "08:00am",
                end: "12:00pm",
            },
        },
        {
            name: "David",
            role: "nurse",
            shift: {
                start: "12:00pm",
                end: "06:00pm",
            },
        },
        {
            name: "Jane",
            role: "care assistant",
            shift: {
                start: "08:00am",
                end: "12:00pm",
            },
        },
        // {
        //     name: "Martha",
        //     role: "care assistant",
        //     shift: {
        //         start: "12:00pm",
        //         end: "06:00pm",
        //     },
        // },
    ],

    tasks: [
        {
            supportPersonel: "care assistant",
            noSupportPersonel: 2,
            time: "09:00am",
            su: "Jane smith",
        },
        {
            supportPersonel: "nurse",
            noSupportPersonel: 2,
            time: "12:00pm",
            su: "Jane smith",
        },
        {
            supportPersonel: "care assistant",
            noSupportPersonel: 1,
            time: "04:00pm",
            su: "Jane smith",
        },
        {
            supportPersonel: "nurse",
            noSupportPersonel: 2,
            time: "02:24pm",
            su: "Jane smith",
        },
        {
            supportPersonel: "care assistant",
            noSupportPersonel: 1,
            time: "10:00am",
            su: "Martha paul",
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '10:00am',
            su: 'Martha paul',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Mary Jane',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Dave Bramble',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Jane smith',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '10:00am',
            su: 'Martha paul',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '10:00am',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'care assistant',
            noSupportPersonel: 1,
            time: '04:00pm',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '02:24pm',
            su: 'Chun Yun',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '08:00am',
            su: 'John Doe',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Jane Smith',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '10:00am',
            su: 'Mary Johnson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '11:00am',
            su: 'David Brown',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Sarah Davis',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '08:00am',
            su: 'Michael Wilson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Emily Thompson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '10:00am',
            su: 'Daniel Martinez',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '11:00am',
            su: 'Olivia Anderson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'James Wilson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '08:00am',
            su: 'Mandy Johnson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Mary Smith',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '10:00am',
            su: 'Star Jones',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '11:00am',
            su: 'John Doe',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Emily Thompson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '08:00am',
            su: 'David Brown',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Jane Smith',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '10:00am',
            su: 'Mary Johnson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '11:00am',
            su: 'David Brown',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '12:00pm',
            su: 'Sarah Davis',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '08:00am',
            su: 'Michael Wilson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '09:00am',
            su: 'Emily Thompson',
        },
        {
            supportPersonel: 'nurse',
            noSupportPersonel: 2,
            time: '10:00am',
            su: 'Daniel Martinez',
        },


    ],
};

export default testData;
