const testData = {
    serviceUsers: [
        {
            id: 1,
            firstName: "John",
            lastName: "Smith",
            tasks: [
                {
                    taskId: 1,
                    userId: 1,
                    description: "Administer medication",
                    timeOfDay: "Morning",
                    hourOfDay: "08:00:00",
                    priority: "High",
                    taskType: "Nurse",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 2,
                    userId: 1,
                    description: "Assist with bathing",
                    timeOfDay: "Morning",
                    hourOfDay: "09:00:00",
                    priority: "Medium",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 3,
                    userId: 1,
                    description: "Prepare meals",
                    timeOfDay: "Afternoon",
                    hourOfDay: "12:00:00",
                    priority: "Low",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 4,
                    userId: 1,
                    description: "Assist with medication",
                    timeOfDay: "Afternoon",
                    hourOfDay: "14:00:00",
                    priority: "High",
                    taskType: "Nurse",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 5,
                    userId: 1,
                    description: "Provide companionship",
                    timeOfDay: "Evening",
                    hourOfDay: "18:00:00",
                    priority: "Medium",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 6,
                    userId: 1,
                    description: "Assist with mobility",
                    timeOfDay: "Evening",
                    hourOfDay: "20:00:00",
                    priority: "Low",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
            ]
        },
        {
            id: 2,
            firstName: "Sarah",
            lastName: "Martinez",
            tasks: [
                {
                    taskId: 11,
                    userId: 2,
                    description: "Help walk",
                    timeOfDay: "Morning",
                    hourOfDay: "08:00:00",
                    priority: "High",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 7,
                    userId: 1,
                    description: "Assist with dressing",
                    timeOfDay: "Morning",
                    hourOfDay: "07:00:00",
                    priority: "Medium",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 8,
                    userId: 1,
                    description: "Administer medication",
                    timeOfDay: "Morning",
                    hourOfDay: "10:00:00",
                    priority: "High",
                    taskType: "Nurse",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 9,
                    userId: 1,
                    description: "Assist with exercises",
                    timeOfDay: "Afternoon",
                    hourOfDay: "15:00:00",
                    priority: "Medium",
                    taskType: "Physiotherapist",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 10,
                    userId: 1,
                    description: "Provide emotional support",
                    timeOfDay: "Evening",
                    hourOfDay: "19:00:00",
                    priority: "Low",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
            ]
        },
        // More service users...
        {
            id: 3,
            firstName: "Michael",
            lastName: "Johnson",
            tasks: [
                {
                    taskId: 12,
                    userId: 3,
                    description: "Assist with meals",
                    timeOfDay: "Afternoon",
                    hourOfDay: "12:00:00",
                    priority: "Medium",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 13,
                    userId: 3,
                    description: "Help with bathing",
                    timeOfDay: "Morning",
                    hourOfDay: "09:00:00",
                    priority: "High",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 14,
                    userId: 3,
                    description: "Administer medication",
                    timeOfDay: "Morning",
                    hourOfDay: "10:30:00",
                    priority: "High",
                    taskType: "Nurse",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 15,
                    userId: 3,
                    description: "Assist with exercises",
                    timeOfDay: "Afternoon",
                    hourOfDay: "14:30:00",
                    priority: "Medium",
                    taskType: "Physiotherapist",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 16,
                    userId: 3,
                    description: "Provide emotional support",
                    timeOfDay: "Evening",
                    hourOfDay: "18:30:00",
                    priority: "Low",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 17,
                    userId: 3,
                    description: "Assist with dressing",
                    timeOfDay: "Morning",
                    hourOfDay: "07:30:00",
                    priority: "Medium",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 18,
                    userId: 3,
                    description: "Help walk",
                    timeOfDay: "Morning",
                    hourOfDay: "08:30:00",
                    priority: "High",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                // More tasks...
            ]
        },
        {
            id: 4,
            firstName: "Emily",
            lastName: "Davis",
            tasks: [
                {
                    taskId: 19,
                    userId: 4,
                    description: "Provide companionship",
                    timeOfDay: "Evening",
                    hourOfDay: "18:00:00",
                    priority: "Low",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 20,
                    userId: 4,
                    description: "Assist with meal preparation",
                    timeOfDay: "Morning",
                    hourOfDay: "09:00:00",
                    priority: "Medium",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 21,
                    userId: 4,
                    description: "Monitor vital signs",
                    timeOfDay: "Afternoon",
                    hourOfDay: "13:00:00",
                    priority: "High",
                    taskType: "Nurse",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 22,
                    userId: 4,
                    description: "Assist with personal hygiene",
                    timeOfDay: "Morning",
                    hourOfDay: "10:00:00",
                    priority: "Medium",
                    taskType: "Care Assistant",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 23,
                    userId: 4,
                    description: "Administer medication",
                    timeOfDay: "Evening",
                    hourOfDay: "19:00:00",
                    priority: "High",
                    taskType: "Nurse",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },
                {
                    taskId: 24,
                    userId: 4,
                    description: "Assist with exercises",
                    timeOfDay: "Afternoon",
                    hourOfDay: "15:00:00",
                    priority: "Medium",
                    taskType: "Physiotherapist",
                    taskGroup: "Routine",
                    taskDate: "2024-02-12",
                },

                // More tasks...
            ]
        },
        // More service users...
    ],
    employees: [
        {
            id: 1,
            firstName: "John",
            lastName: "Doe",
            jobTitle: "Care Assistant",
            shift: "Morning"
        },
        {
            id: 2,
            firstName: "Jane",
            lastName: "Smith",
            jobTitle: "Nurse",
            shift: "Morning"
        },
        {
            id: 3,
            firstName: "David",
            lastName: "Johnson",
            jobTitle: "Care Assistant",
            shift: "Afternoon"
        },
        {
            id: 4,
            firstName: "Emma",
            lastName: "Wilson",
            jobTitle: "Nurse",
            shift: "Evening"
        },
    ]
};

export default testData;
